import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.amazon.in/');
  await page.getByRole('link', { name: 'Hello, sign in Account & Lists' }).click();
  await page.getByRole('textbox', { name: 'Enter mobile number or email' }).click();
  await page.getByRole('textbox', { name: 'Enter mobile number or email' }).dblclick();
  await page.waitForTimeout(1000);
  await page.getByRole('textbox', { name: 'Enter mobile number or email' }).fill('laxmidhanu28@gmail.com');
  await page.getByRole('textbox', { name: 'Enter mobile number or email' }).press('Enter');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
    await page.waitForTimeout(1000);

  await page.getByRole('textbox', { name: 'Password' }).fill('New@2026');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('link', { name: 'AmazonBasics' }).click();
  await page.locator('[id="1"]').getByRole('img').click();
  await page.getByRole('link', { name: 'Amazon Basics Travel Neck' }).click();
  await page.goto('https://www.amazon.in/Amazon-Basics-Travel-Pillow-Comfortable/dp/B0DFMHFMJ3/ref=s9_acsd_al_bw_cv2_1_0_t?_encoding=UTF8&pf_rd_m=A21TJRUUN4KGV&pf_rd_s=merchandised-search-3&pf_rd_r=VATBH3BBT23VSAGJRF2S&pf_rd_p=75fde330-7be7-4158-8a2b-9c848ce8f6c7&pf_rd_t=&pf_rd_i=6637738031&th=1');
  await page.getByRole('button', { name: 'Add to cart', exact: true }).click();
  await page.getByLabel('Add to cart', { exact: true }).click();
  await page.getByLabel('Add to cart', { exact: true }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Add to cart', exact: true }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('#a-autoid-2-announce').getByText('Select quantity').click();
  await page.getByLabel('Add to cart', { exact: true }).click();
  await page.getByLabel('Buy Now').click();
  await page.getByText('Quantity:Select quantity').click();
  await page.getByText('Quantity:Select quantity').click();
  await page.getByText('Quantity:Select quantity').click();
  await page.getByText('Quantity:Select quantity').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Add to cart', exact: true }).click();
  await page.locator('#a-autoid-2-announce').getByText('Select quantity').click();
  await page.locator('#a-autoid-2-announce').getByText('Select quantity').click();
  await page.getByRole('button', { name: 'Add to cart', exact: true }).click();
});